#!/bin/bash

TARGETDIR=boweb/static/jslib
mkdir -p $TARGETDIR

wget http://code.jquery.com/jquery.min.js -O $TARGETDIR/jquery.min.js
wget http://mbostock.github.com/d3/d3.v2.min.js  -O $TARGETDIR/d3.v2.min.js
wget https://raw.github.com/corbanbrook/dsp.js/master/dsp.js -O $TARGETDIR/dsp.js
wget https://raw.github.com/cloudhead/less.js/master/dist/less-1.3.3.min.js -O $TARGETDIR/less-1.3.3.min..js

SLICKGRID_ARCHIVE=$(mktemp /tmp/slickgrid_tar_gz_XXXXXXXXXX)
wget https://github.com/mleibman/SlickGrid/archive/2.02.tar.gz -O $SLICKGRID_ARCHIVE
tar xvzf $SLICKGRID_ARCHIVE --strip-components 1 --no-anchored -C $TARGETDIR slick.core.js
rm -rf $SLICKGRID_ARCHIVE

JQUERY_UI_ARCHIVE=$(mktemp /tmp/jquery_ui_zip_XXXXXXXXXX)
echo $JQUERY_UI_ARCHIVE
wget http://jqueryui.com/download/jquery-ui-1.8.20.custom.zip -O $JQUERY_UI_ARCHIVE
